services:
    db:
        image: mysql:5.7
        ports:
            - "3307:3306"
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_DATABASE}
            MYSQL_DATABASE: ${MYSQL_USER}
            MYSQL_USER: ${MYSQL_PASSWORD}
            MYSQL_PASSWORD: ${MYSQL_ROOT_PASSWORD}
        volumes:
            - db-data:/var/lib/mysql

    app:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - "8080:80"
        volumes:
            - .:/var/www/html
        depends_on:
            - db
        command:
            sh -c "php bin/console cache:clear && apache2-foreground"


volumes:
    db-data:
